/* global window */
/* Service definitions - one source of truth for the four service pages.
   Structure matches the BATCH 2 flow: hero, challenges, deliver, ecosystem,
   outcomes, metrics-placeholder, related story, next service, CTA. */
window.SERVICES = {
  cloud: {
    slug: "cloud", tint: "blue", title: "Cloud & Infrastructure Transformation",
    headline: "Modern infrastructure built for resilience, scale, and control.", hl: "resilience, scale, and control",
    sub: "Digital transformation starts with strong foundations. ICT pairs digital strategy and enterprise architecture with cloud, network, and data-centre modernisation, helping organisations move to hybrid and multi-cloud, transform networks, and re-engineer processes without compromising security, performance, or continuity.",
    challengeLead: "Infrastructure wasn't built for today's demands.",
    challengeSub: "Organisations are under increasing pressure to modernise while maintaining uptime, security, and operational stability.",
    challenges: ["Legacy infrastructure limiting agility", "Rising operational costs", "Data sovereignty requirements", "Complex cloud adoption programmes", "Capacity constraints", "Business continuity concerns", "Fragmented infrastructure environments"],
    deliver: [
      { icon: "compass", h: "Digital Strategy & Consulting", p: "Digital transformation consulting, technology strategy, and roadmaps aligned to business priorities." },
      { icon: "layers", h: "Enterprise Architecture & Modernisation", p: "Enterprise architecture and IT modernisation that turn legacy estates into agile, scalable foundations." },
      { icon: "cloud", h: "Hybrid & Multi-Cloud Architecture", p: "Design and operation of public, private, hybrid, and multi-cloud environments." },
      { icon: "azure", h: "Cloud Migration & Optimisation", p: "Accelerate cloud adoption while maintaining governance, cost control, and operational continuity." },
      { icon: "network", h: "Network Transformation", p: "Software-defined networking and network transformation for resilient, high-performance connectivity." },
      { icon: "workplace", h: "Unified Communications", p: "Unified communications and collaboration platforms that connect a distributed workforce." },
      { icon: "data", h: "Data Centres & Virtualisation", p: "High-performance data centres, virtualisation, and infrastructure engineered for demanding workloads." },
      { icon: "improve", h: "Business Process Transformation", p: "Business process re-engineering and automation that streamline how work gets done." },
    ],
    ecosystem: ["Microsoft Azure"],
    outcomes: [
      { icon: "shield", h: "Improved Infrastructure Resilience", p: "Reduce operational risk and improve continuity." },
      { icon: "bolt", h: "Faster Deployment Cycles", p: "Accelerate delivery of new services and environments." },
      { icon: "compass", h: "Better Cloud Governance", p: "Improve visibility, control, and cost management." },
      { icon: "layers", h: "Enhanced Scalability", p: "Support future growth without infrastructure bottlenecks." },
      { icon: "operations", h: "Simplified Operations", p: "Reduce complexity across hybrid environments." },
      { icon: "improve", h: "Stronger DR Readiness", p: "Improve business continuity and resilience." },
    ],
    metrics: { required: ["Migration timelines", "Availability / uptime figures", "Cost-optimisation results"], examples: ["Reduced infrastructure footprint by [X]%.", "Migrated [X] workloads within [Y] hours of planned downtime.", "Improved platform availability to [X]%."] },
    story: { sector: "Public Sector", h: "Modernising the data centre with hybrid cloud", p: "Discover how ICT helped a public-sector organisation extend its on-premises infrastructure into Azure while maintaining governance, security, and operational continuity.", href: "Public-Sector.html" },
    next: { h: "Cybersecurity & Digital Resilience", p: "Modern infrastructure requires security embedded into every layer.", href: "Cybersecurity-Digital-Resilience.html" },
    cta: "Let's modernise your infrastructure.",
  },

  cybersecurity: {
    slug: "cybersecurity", tint: "violet", title: "Cybersecurity & Digital Resilience",
    headline: "Security engineered into every layer of the enterprise.", hl: "every layer",
    sub: "Cybersecurity is no longer a standalone function. It must be embedded across infrastructure, applications, identities, data, and operations. ICT helps organisations build resilient environments that defend against evolving threats while supporting business growth.",
    challengeLead: "The threat landscape continues to evolve.",
    challengeSub: "Security and resilience now sit at board level, and the pressure on enterprises in Qatar keeps rising.",
    challenges: ["Sophisticated cyber threats", "Regulatory requirements", "Cloud security risks", "Identity attacks", "Data protection obligations", "Operational resilience requirements"],
    deliver: [
      { icon: "compass", h: "Security Strategy & Governance", p: "Align security investments with business priorities and risk profiles." },
      { icon: "radar", h: "Next-Generation SOC Services", p: "Continuous monitoring, threat detection, and response from a modern security operations centre." },
      { icon: "identity", h: "Identity & Access Management", p: "Protect users, applications, and critical assets with strong identity controls." },
      { icon: "lock", h: "Zero Trust Architecture", p: "Reduce attack surfaces and verify every access request across the estate." },
      { icon: "shield", h: "Threat Intelligence & Incident Response", p: "Rapid detection, investigation, and response to security incidents." },
      { icon: "target", h: "Managed Detection & Response", p: "MDR and XDR across endpoints, identities, cloud, and data." },
      { icon: "data", h: "Data Protection & Encryption", p: "Safeguard sensitive data with encryption, governance, and loss prevention." },
      { icon: "check", h: "DevSecOps & Compliance", p: "Application and cloud security testing built into delivery, aligned to ISO, NIST, and local regulations." },
    ],
    ecosystem: ["Microsoft Security", "F5", "Forcepoint", "Tenable", "Imperva", "Checkmarx", "Imprivata"],
    outcomes: [
      { icon: "shield", h: "Stronger Security Posture", p: "Reduce exposure to cyber threats." },
      { icon: "radar", h: "Faster Threat Detection", p: "Improve visibility and response." },
      { icon: "compass", h: "Improved Governance", p: "Align security with organisational objectives." },
      { icon: "check", h: "Enhanced Compliance Readiness", p: "Support evolving regulatory requirements." },
      { icon: "target", h: "Reduced Operational Risk", p: "Strengthen resilience across technology environments." },
      { icon: "lock", h: "Better Protection of Critical Assets", p: "Safeguard data, applications, and infrastructure." },
    ],
    metrics: { required: ["Mean time to detect / respond", "Compliance coverage", "Risk-reduction results"], examples: ["Reduced mean time to detect from [X] hours to [Y] minutes.", "Achieved compliance with [framework] across [X] systems.", "Reduced the external attack surface by [X]%."] },
    story: { sector: "Education & Research", h: "AI-powered unified enterprise search", p: "See how ICT implemented secure access controls and governance to enable knowledge discovery while protecting sensitive information.", href: "Education-Research.html" },
    next: { h: "AI & Intelligent Automation", p: "Unlock intelligence while maintaining governance and control.", href: "AI-Intelligent-Automation.html" },
    cta: "Let's strengthen your security posture.",
  },

  ai: {
    slug: "ai", tint: "magenta", title: "AI & Intelligent Automation",
    headline: "Moving AI from experimentation to enterprise value.", hl: "enterprise value",
    sub: "AI creates value when it becomes part of everyday operations. ICT turns data into insight and automation into outcomes, spanning data platforms and analytics, enterprise applications and integration, customer experience platforms, and emerging technologies, all delivered on secure, governed, production-ready foundations.",
    challengeLead: "Most organisations aren't struggling with AI ideas. They're struggling with AI adoption.",
    challengeSub: "The gap between a promising pilot and production value is where most initiatives stall.",
    challenges: ["Data readiness", "AI governance", "Security concerns", "Integration complexity", "Lack of operationalisation", "Scaling successful pilots"],
    deliver: [
      { icon: "ai", h: "Enterprise AI & Machine Learning", p: "Production-ready AI and machine learning platforms built for scale and governance." },
      { icon: "data", h: "Data Platforms & Analytics", p: "Enterprise data platforms, data lakes, business intelligence, and predictive and prescriptive analytics." },
      { icon: "operations", h: "Agentic & Autonomous AI", p: "Intelligent agents and multi-agent systems that reason, plan, and act across complex workflows." },
      { icon: "improve", h: "Intelligent Process Automation", p: "Automate manual processes and streamline operations end to end." },
      { icon: "workplace", h: "Enterprise Applications & Integration", p: "ERP, CRM, and HRMS implementation with API management and enterprise integration." },
      { icon: "layers", h: "Low-Code & No-Code Development", p: "Build and adapt business applications quickly with low-code and no-code platforms." },
      { icon: "target", h: "Customer Experience Platforms", p: "Omnichannel experiences, eCommerce, and web and mobile apps with personalisation and customer journey transformation." },
      { icon: "network", h: "Emerging Technologies", p: "IoT, blockchain, AR/VR, and digital twins applied to real business problems." },
      { icon: "shield", h: "Responsible & Secure AI", p: "Governance, compliance, and security embedded into every AI initiative." },
    ],
    ecosystem: ["Microsoft Azure AI", "Databricks", "Dataiku", "Informatica", "Striim"],
    outcomes: [
      { icon: "bolt", h: "Faster Decision Making", p: "Provide faster access to trusted information." },
      { icon: "improve", h: "Improved Operational Efficiency", p: "Reduce manual effort across critical workflows." },
      { icon: "compass", h: "Better Information Discovery", p: "Connect people with knowledge across systems." },
      { icon: "shield", h: "Stronger Governance", p: "Ensure AI remains secure and compliant." },
      { icon: "target", h: "Increased Productivity", p: "Help teams focus on higher-value work." },
      { icon: "check", h: "Enterprise-Ready AI Adoption", p: "Move beyond pilots into production." },
    ],
    metrics: { required: ["Automation / efficiency gains", "Time-to-value", "Adoption metrics"], examples: ["Automated [X]% of a target manual process.", "Reduced processing time per case from [X] minutes to [Y].", "Delivered the first production use case within [X] weeks."] },
    story: { sector: "Financial Services", h: "Intelligent investment research assistant", p: "Discover how ICT transformed fragmented investment information into a governed, AI-powered research platform.", href: "Financial-Services.html" },
    next: { h: "Managed & Support Services", p: "Ensure AI platforms continue performing long after deployment.", href: "Managed-Support-Services.html" },
    cta: "Let's operationalise AI.",
  },

  managed: {
    slug: "managed", tint: "orange", title: "Managed & Support Services",
    headline: "Technology operations that never stop evolving.", hl: "never stop evolving",
    sub: "Technology environments require continuous attention. ICT provides managed services that help organisations maintain, optimise, secure, and improve critical technology environments long after implementation.",
    challengeLead: "The real challenge begins after deployment.",
    challengeSub: "Keeping mission-critical environments available, secure, and improving is a discipline of its own.",
    challenges: ["Limited internal resources", "Monitoring gaps", "Operational complexity", "Security management", "Performance issues", "Business continuity requirements"],
    deliver: [
      { icon: "layers", h: "Managed IT & Infrastructure Operations", p: "24/7 monitoring and management of critical infrastructure and IT operations." },
      { icon: "cloud", h: "Managed Cloud Operations", p: "Optimise cloud performance, governance, and cost." },
      { icon: "shield", h: "Managed Security Services", p: "Strengthen protection through continuous monitoring and response." },
      { icon: "managed", h: "Application Support", p: "Maintain stability and performance across critical systems." },
      { icon: "improve", h: "Business Continuity & Disaster Recovery", p: "Prepare for disruption and maintain resilience." },
      { icon: "operations", h: "ITSM-Aligned Support", p: "Structured support aligned with operational best practices." },
    ],
    ecosystem: ["Monitoring Platforms", "Cloud Platforms", "Security Platforms", "ITSM Platforms", "Infrastructure Platforms", "Analytics Platforms"],
    outcomes: [
      { icon: "check", h: "Improved Service Availability", p: "Support reliable business operations." },
      { icon: "layers", h: "Reduced Operational Complexity", p: "Simplify day-to-day management." },
      { icon: "bolt", h: "Faster Issue Resolution", p: "Respond to incidents more effectively." },
      { icon: "target", h: "Better User Experience", p: "Improve service performance and stability." },
      { icon: "shield", h: "Enhanced Operational Resilience", p: "Reduce disruption and downtime." },
      { icon: "improve", h: "Long-Term Technology Value", p: "Protect and optimise technology investments." },
    ],
    metrics: { required: ["Service availability against SLA", "Incident resolution times", "Workload-reduction results"], examples: ["Maintained [X]% service availability against SLA.", "Resolved [X]% of incidents within SLA targets.", "Reduced mean time to resolve by [X]%."] },
    story: { sector: "Public Sector", h: "Modernising the data centre with hybrid cloud", p: "See how operational continuity was maintained throughout a large-scale transformation programme.", href: "Public-Sector.html" },
    next: { h: "Cloud & Infrastructure Transformation", p: "Explore how ICT helps organisations modernise technology foundations.", href: "Cloud-Infrastructure-Transformation.html" },
    cta: "Let's optimise your operations.",
  },
};
